### PR TITLE
forms_valid now calls FormMixins.form_valid prior to saving - with tests

### PR DESCRIPTION
**Pull request by howieweiner**
Hi Andrew. I finally got round to updating the test case for this test. Took me a while as a) I've never written Django unit tests, which is shocking as I seem to have made a career from writing Java ones. and b) I'm new to GitHub. Let me know if I've screwed up anywhere along the way.

Please merge if you are happy.

Thanks

### CODE REVIEW

**Comment by jonashaag** [comment]
What's the rationale behind this?

**Comment by howieweiner** [comment]
Hi

It's a long time since I've used this library, but from memory, there was no check to see if the main form was valid before attempting to saving it along with the inline forms. As a result, if the main form is invalid, there is no validation message

**Comment by jonashaag** [comment]
This look reasonable to me. A few things should be changed and tested before we can land this:

- [ ] `form_valid` should be called on the inlines as well
- [ ] `.save()` should not have to be called explicitly, as it is implied by `.form_valid`
- [ ] `form_invalid` should probably be called from `forms_invalid` accordingly
- [ ] The patch should not contain unrelated whitespace changes

**Comment by jonashaag** [comment]
Closing due to inactivity.

**Pull request closed without merging**
