### PR TITLE
Introduce SuccessMessageWithInlinesMixin

### PR DESCRIPTION
**Pull request by xrmx**
Add a simple mixin for displaying a message with django.contrib.messages following django.contrib.messages.views spirit

### CODE REVIEW

**Comment by auvipy** [comment]
why bringing full code from contrib.message.view? is it possible to inherit the SuccessMessageMixin Class?

from django.contrib import messages


class SuccessMessageMixin(object):
    """
    Adds a success message on successful form submission.
    """
    success_message = ''

    def form_valid(self, form):
        response = super(SuccessMessageMixin, self).form_valid(form)
        success_message = self.get_success_message(form.cleaned_data)
        if success_message:
            messages.success(self.request, success_message)
        return response

    def get_success_message(self, cleaned_data):
        return self.success_message % cleaned_data

**Comment by xrmx** [comment]
@auvipy i think you are missing the *s* in forms_valid.

**Comment by jonashaag** [comment]
This should go to contrib.

**Comment by xrmx** [comment]
Thanks @jlucchese @jonashaag !

**Pull request merged**
