### PR TITLE
using django vanilla views for to refactor extra-views

### PR DESCRIPTION
**Pull request by auvipy**
bringing up an old patch

### CODE REVIEW

**Comment by jonashaag** [comment]
Closing due to inactivity.

**Comment by auvipy** [comment]
extracted as a different package https://github.com/auvipy/django-vanilla-extensions

**Comment by jonashaag** [comment]
@auvipy I'm still open for refactoring extra-views with vanilla-views :)

**Comment by auvipy** [comment]
issue is that will break many things :)

**Pull request closed without merging**
