### PR TITLE
Add Django 2.2, 3.0(a) to tests, dropped Django 2.0, py3.4

### LINKED ISSUE #196: django 2.2 & 3.0a+ support

### PR DESCRIPTION
**Pull request by therefromhere**
Resolves #196

### CODE REVIEW

**Comment by therefromhere** [comment]
I'm not sure why some of the tests are failing on travis, tox is passing for me locally.

It seems to be something specific to Django>=2.2, maybe something subtly wrong with the settings setup in runtests.py?  I'd be tempted to remove nose/runtests.py and see if it goes away with pytest-django and a more normal settings file in tests/settings.py.

**Comment by therefromhere** [comment]
(for what it's worth I'm using django-extra-views with Django 2.2 in prod with no issues).

**Comment by jonashaag** [comment]
If we can easily get rid of nose I'm all for it.

**Comment by therefromhere** [comment]
I think it's because of this ``from django.contrib.contenttypes.models import ContentType`` in ``extra_views_tests/models.py``.

Also there are no migrations for the extra_views_tests models.

**Comment by therefromhere** [comment]
I've fixed the tests, the failure was because extra_views_tests has models but didn't have migrations.
No idea why it was passing locally and failing on travis though.  Should be all good now.

**Comment by jonashaag** [comment]
Boy these codecov comments are annoying

**Comment by jonashaag** [comment]
Thanks!

**Pull request merged**
