### PR TITLE
Revert view.object back to original value if inline validation fails

### PR DESCRIPTION
**Pull request by sdolemelipone**
As per issue #155.

@Murfen please confirm if this resolves the issue for you.

### CODE REVIEW

**Comment by jonashaag** [comment]
Is this consistent with Django‘s behavior?

**Comment by jonashaag** [comment]
Maybe we should provide another way to distinguish the cases rather than implicitly providing that state through the absence of a variable. 

„Any sufficiently complicated model class contains an ad-hoc, informally-specified, bug-ridden, slow implementation of half of a state machine.“

**Comment by sdolemelipone** [comment]
Yes the specification "`self.object` is `None` for Create views, but is a model instance for Update views" is definitely an implicit one, even if it is originally in Django's code not ours! 

As a boolean I think it would be sufficient to check `self.object.pk` in template languages and `getattr(self.object, 'pk', None)` in Python.

Templates may use `self.object` in rendering data on the page; for a CreateView that means `self.object` will be 
* `None` on a GET request.
* `None` on a response to a PUT request if form fails to validate.
* An instance of `view.Model` on a response to a PUT request if the form validates but the inline formsets do not. 

That does seem like an inconsistent situation for template writers to deal with. And one that doesn't occur with the simpler Django CreateView. 

I agree it's not a pretty change. So perhaps @Murfen could tell us if there are situations that aren't addressed by my suggestion of checking `self.object.pk`?

**Comment by jonashaag** [comment]
Ok never mind my comment about implicit state. This is a Django design issue that we ought not to deal with here

**Comment by sdolemelipone** [comment]
:+1: Ok thanks. I think we should leave this open for further comments before merging/closing.

**Comment by jonashaag** [comment]
@sdolemelipone Can we merge this? Yes right?

**Comment by sdolemelipone** [comment]
Hey @jonashaag, yes we can. I'll do the merge tomorrow.

**Comment by sdolemelipone** [comment]
Or today :-)

**Pull request merged**
