### PR TITLE
Use items over iteritems in multi.py.

### PR DESCRIPTION
**Pull request by mrben**
Hello

First off, thanks for making this library, I use it in pretty much every Django project.

This PR swaps `iteritem` for `items` in `multi.py` so that Py3k doesn't blow up. I understand that this module is not support but wondered if you'd consider merging this in nonetheless.

Cheers
Ben.

### CODE REVIEW

**Comment by jonashaag** [comment]
Thanks for the patch. However, I believe Python 3 support should be tackled in one go rather than many small changes.

**Comment by mrben** [comment]
Ah, I thought [Python 3 was already supported](https://github.com/AndrewIngram/django-extra-views/blob/0.7.1/setup.py#L27) and this hadn't been converted because it's an unsupported module.

**Comment by jonashaag** [comment]
Oops. You're right. Anyways, multi will go away in the next release, sorry.

**Comment by mrben** [comment]
That's a shame. Most used module for me :-). Thanks for the heads-up though.

**Pull request closed without merging**
