### PR TITLE
Formset kwargs

### PR DESCRIPTION
**Pull request by jonashaag**
Looking for feedback and opinions here.

Still to do:
- [ ] Add deprecation for old attributes.
- [ ] Add tests. Turns out that there wasn't a single test for things like `max_num`.
- [ ] Update changelog and documentation.

### CODE REVIEW

**Comment by jonashaag** [comment]
@screendriver @throwable-one @AndrewIngram

**Comment by sdolemelipone** [comment]
I'm working on a pull request for this at the moment. Given that the code base has moved on a lot since 2015, is it worth just opening a new PR forked from the latest master or continuing with this one?

Also, @jonashaag  do you recall the rationale for leaving `can_delete` as a class level attribute? It seems fairly arbitrary to me. The only one I would leave is `initial`, given how useful `get_initial` can be.

**Comment by sdolemelipone** [comment]
Ah, I understand - it's because `can_delete` varies based on the class.

**Comment by jonashaag** [comment]
> I'm working on a pull request for this at the moment

That's good to hear :)

> Given that the code base has moved on a lot since 2015, is it worth just opening a new PR forked from the latest master or continuing with this one?

Whatever you prefer.

**Pull request closed without merging**
