### PR TITLE
Add Python 3.11

### PR DESCRIPTION
**Pull request by sdolemelipone**
Also corrected obselete `whitelist_externals` tox flag to `allowlist_externals`.

### CODE REVIEW

**Comment by sdolemelipone** [comment]
FYI I've removed 3.5, 3.6 because they were no longer supported by the automated test suite tools (being obselete).

**Comment by jonashaag** [comment]
Is there an easy way to keep testing the old versions, eg. by pinning the testing tools to an older version? I’m in favor of keeping compat if it doesn’t cost a lot of effort.

**Comment by sdolemelipone** [comment]
Yep I can see what's possible. I won't be able to do much for the next week as I'm on holiday with poor internet connection, but can pick it up when I get back.

**Comment by sdolemelipone** [comment]
Forcing the runner use ubuntu 20.04 rather than 22.04 allowed the tests to still run for Python 3.5+ :-) This should work fine until a new version of python is released which ubuntu 20.04 does not support.

**Review by jonashaag — APPROVED** [review]

**Pull request merged**
