### PR TITLE
Refactoring forms_valid method

### PR DESCRIPTION
**Pull request by bcanyelles**
This refactor allows you to override the `form_valid` method of the `ModelFormWithInlinesMixin` views which currently it doesn't work (it never runs).

### CODE REVIEW

**Comment by sdolemelipone** [comment]
Hi @jonashaag, what improvements were you thinking of here? A test to ensure that form_valid is called?

**Comment by jonashaag** [comment]
I believe this didn’t apply cleanly at some point but it looks good now. Test would be great.

**Comment by jonashaag** [comment]
LGTM!

**Comment by sdolemelipone** [comment]
Thanks! :-)

**Pull request merged**
