### PR TITLE
fields should'nt be __all__ if form_class is set

### PR DESCRIPTION
**Pull request by saz**
This will result in problems with Django version 1.6 and newer as all form fields are added to the form

### CODE REVIEW

**Comment by sergei-maertens** [comment]
:+1: 

However, I think you should check `self.get_form_class()` instead of just checking `self.form_class`

**Comment by ryanbagwell** [comment]
@AndrewIngram any chance you can merge this?

**Comment by jonashaag** [comment]
Please describe the rationale for this change in more detail (best as a code comment) and add a test case.

**Comment by sergei-maertens** [comment]
I can chime in for the rationale:

I ran into this with a ModelForm that had a ModelChoiceField with a ton of options, leading to a non-performant form when rendering those options with the default widget. My intended solution was to limit the fields (MyForm.Meta.fields) to those that I need, excluding the non-performant field in that case.

Then it turns out that even with the specified fields on the form, the mixin was still applying ``__all__``, causing that field I wanted to exclude to be included anyway.

I suppose you could specify the fields on the formset mixin, but that violates the DRY principles, since you've already defined them on the form itself.

**Comment by jonashaag** [comment]
@sergei-maertens thanks! This makes sense, but since Django < 1.7 has reached its end of extended support effective October 1 2015, I think we should be able to drop support for these versions.

**Comment by sergei-maertens** [comment]
I'm sorry, but I would vote to keep this open or track it in a different ticket then, because the issue is still standing. The ``self.fields = '__all__'`` code has to be removed then for newer versions, or maybe just remove the version check and stick with the ``form_class is None`` check.

I would probably be able to provide a (failing) test case in the course of this week, but I'd rather keep this PR/issue open to not forget it.

**Comment by jonashaag** [comment]
With Django >= 1.6, do we even have to special case the `fields` attribute somehow? I believe it should be possible to just pass it down to `inlineformset_factory` and let Django do the rest. I don't think we should be setting `__all__` in the first place, even if it's backwards-incompatible with older django-extra-views versions. It's backwards-incompatible in Django after all.

**Comment by sergei-maertens** [comment]
I'm going off the top of my head now, but if you then use a ModelForm (with custom validation) for instance, then you're still required to specify ``fields`` on the formset mixin AND on the ModelForm, right? If that's the case, that doesn't make sense in my eyes, it's a direct violation of DRY.

This is the relevant code in my project:

* https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/src/brouwers/builds/views.py#L83
* https://github.com/modelbrouwers/modelbrouwers/blob/feature/builds/src/brouwers/builds/forms.py#L24

**Comment by sergei-maertens** [comment]
Looking at the actual code for the modelformset_factory it seems you could pass in ``fields`` directly indeed, but that would indeed require the removal of the version check branch.

**Pull request closed without merging**
