### PR TITLE
Added messages support

### PR DESCRIPTION
**Pull request by freeworlder**
Issue #59

### CODE REVIEW

**Comment by freeworlder** [comment]
Checks are failing as there is not django contrib messages module found that is required for messages to work.

**Comment by jcuotpc** [comment]
Is there a way to get the context data from the InlineFormSet to customize the success message?

**Comment by sdolemelipone** [comment]
Hi @freeworlder, I have coded a change that will pass the middleware into the test environment and fix the tests. There should be a box to allow contributors to push updates to your PR, if you tick that I will push it.

**Comment by sdolemelipone** [comment]
Ah, I see that box is for maintainers only. In that case, here you go. This only works from Django 1.10 onwards as I think the name of the middleware module has changed. As the master branch is only supporting Django 1.11+ this won't be a problem.

runtests.py:
```
if not settings.configured:
    settings.configure(
        ...
        MIDDLEWARE=[
            'django.middleware.security.SecurityMiddleware',
            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.common.CommonMiddleware',
            'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',
            'django.contrib.messages.middleware.MessageMiddleware',
            'django.middleware.clickjacking.XFrameOptionsMiddleware',
        ],
        ...
```
Then in extra_views_tests/tests.py find and replace `res.context['request']` with `res.context['view'].request` (2 occurrences).

**Comment by jonashaag** [comment]
Travis tests against the commits applied to the merge target (so, the current master).

I don't think there's much value in keeping commit history accurate; if you want to recognise their contributions you may simply add their name to the commit message.

**Pull request merged**
