### PR TITLE
Always add sort_helper into context in SortableListMixin

### PR DESCRIPTION
**Pull request by lampslave**

### CODE REVIEW

**Comment by jonashaag** [comment]
Hi, thanks for the patch! This needs tests. Please also explain what this change is necessary for.

**Comment by lampslave** [comment]
Hello.
This change allows to get same instance of `sort_helper` in any part of code: before, after or instead of calling `get_queryset` without additional checks. In most cases `sort_helper` will be in context anyway, why we need to check anything? See the [template](https://github.com/AndrewIngram/django-extra-views/blob/master/extra_views_tests/templates/extra_views/sortable_item_list.html#L12-L14), it assumes existence of `sort_helper` in the context.

**Comment by jonashaag** [comment]
Why not simply create the instance in the view's `__init__`?

**Comment by lampslave** [comment]
Because the current version is already doing what is necessary :)

**Comment by jonashaag** [comment]
Are you talking about the version in the master branch or in your branch?

**Comment by lampslave** [comment]
I'm talking about my branch.

**Comment by jonashaag** [comment]
OK, thanks for the clarification. Your branch might be correct, but I wonder if there's a cleaner way to solve the problem, hence the `__init__` question.

**Comment by lampslave** [comment]
OK, no problem, but maybe in another PR.

**Pull request closed without merging**
